version: '2'

services:
  stormmqtt:
    hostname: stormmqtt
    image: pharndt/stormmqtt:${VERSION}
    build: .
    volumes:
      - ./production/config:/var/lib/storm-to-mqtt-gw:ro
    restart: "no"
