project_name: stormsensor
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: stormsensor
    main: ./main.go
    binary: stormsensor
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/philipparndt/stormsensor/version.Version={{.Version}} -X github.com/philipparndt/stormsensor/version.GitCommit={{.Commit}} -X github.com/philipparndt/stormsensor/version.BuildTime={{.Date}}

dockers:
  - image_templates:
      - "pharndt/stormmqtt:{{ .Tag }}-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
    skip_push: false

  - image_templates:
      - "pharndt/stormmqtt:{{ .Tag }}-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
    skip_push: false

docker_manifests:
  - id: tag
    name_template: "pharndt/stormmqtt:{{ .Tag }}"
    image_templates:
      - pharndt/stormmqtt:{{ .Tag }}-amd64
      - pharndt/stormmqtt:{{ .Tag }}-arm64

  - id: latest
    name_template: "pharndt/stormmqtt:latest"
    image_templates:
      - pharndt/stormmqtt:{{ .Tag }}-amd64
      - pharndt/stormmqtt:{{ .Tag }}-arm64

release:
  disable: false
  mode: replace
  draft: false
  prerelease: auto
  make_latest: true
  skip_upload: true
