name: Build release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: Release type
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: philipparndt/get-release-number@v3
        id: next
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          releaseType: ${{ github.event.inputs.releaseType }}

      - uses: actions/setup-go@v5
        with:
          go-version: '1.19.4'

      - name: Build
        working-directory: app
        run: |
          go build .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker container and push
        id: docker_build
        uses: docker/build-push-action@v5
        env:
          RELEASE_VERSION: ${{ steps.next.outputs.version }}
        with:
          context: ./app
          file: ./app/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            pharndt/stormmqtt:latest
            pharndt/stormmqtt:${{env.RELEASE_VERSION}}

      - uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.next.outputs.version }}
          tag: ${{ steps.next.outputs.version }}
          body: |
            Docker tag: `pharndt/stormmqtt: ${{ steps.next.outputs.version }}`

            Changes in this Release
              - Dependency update
              - ...
