name: Application

on:
  push:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install
        working-directory: app
        run: |
          npm install

      - name: Lint/Test
        working-directory: app
        run: |
          npm run lint
          npm test

      - name: Build
        working-directory: app
        run: |
          npm run build

      - name: Build container
        run: docker-compose build
